<package format="3">
  <name>chemistry_laboratory</name>
  <version>0.0.0</version>
  <description>The chemistry_laboratory package</description>

  <maintainer email="lisca@cs.uni-bremen.de">Gheorghe Lisca</maintainer>

  <license>TODO</license>

  <!-- Build tool dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies for building and running the package -->
  <depend>rclcpp</depend>
  <depend>rviz2</depend>
  <depend>robot_state_publisher</depend>
  <depend>urdf</depend>
  <depend>xacro</depend> <!-- Only include if you use Xacro files -->

  <!-- Optional: Dependencies for visualization and meshes -->
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>